-- 협회 업무실적 매핑 SELECT (읽기전용 재현)
-- 원본: apworksdw.dbo.LAW_SOURCETOLAW_NEW 를 변환 — 원본 테이블에 쓰지 않음.
--   @BUNGI/@APPCODE/@MON → {BUNGI}/{APPCODE}/{MON} (내부 검증값만 주입),
--   LAW_KAPATOLAW → 세션 임시테이블 #SEL, INSERT INTO APW_REPAPP 제거,
--   본번/부번 빈값은 협회양식 규칙대로 '0000' 패딩.
-- 선행: 호출측이 #SEL(ID=MASTERID, BUNGI, APPCODE, ID_NUM=DocID, FUSE='Y',
--   LINKNAME=dbo.UFN_LINKNAME(GUBUN_CODE), MON)을 채운 뒤 이 배치를 실행한다.
-- 검증: 2026-05 상반(본사) 128건 셀대조 — 핵심 컬럼 전량 일치(work-report-kapa 메모리).

SELECT I.MASTERID, MAX(REG+EUB+SAN+BUN1+BUN2) REG  
	INTO #I  
	FROM #SEL M   
		JOIN APW_INVENTORY I ON M.ID = I.MASTERID    
	WHERE FUSE = 'Y' AND M.BUNGI = '{BUNGI}' AND M.MON = {MON} AND M.APPCODE = '{APPCODE}'  
	GROUP BY I.MASTERID   
 
	--SELECT * FROM #I   
  
	SELECT '{BUNGI}' [BUNGI], '{APPCODE}' [APPCODE], A.ID_NUM, T.COMMONCODE PCODE   
				,CASE M.GUBUN_CODE WHEN 'CTS' THEN '60' WHEN 'LAN' THEN '50' WHEN 'TKP' THEN '70' ELSE T.YCODE END YCODE  
				
				--,CAST(M.TITLE AS VARCHAR(120)) AS GNAME   --일우 주석 2020.04.13      
				--,CAST(J.GNAME AS VARCHAR(120)) AS GNAME        
				,CASE WHEN CAST(M.TITLE AS VARCHAR(120)) IS NOT NULL THEN CAST(M.TITLE AS VARCHAR(120))  ELSE CAST(J.GNAME AS VARCHAR(120)) END AS GNAME  

				,CAST(M.CUSTNAME AS VARCHAR(60)) AS CUST  
				,M.RECEIPTDATE IN_DATE, M.SENDDATE OUTDATE, D.PRICEPOINTDATE  AS CONSULTDATE  
				, RIGHT('00'+CAST(CAST(U.QUA_NO AS INT) AS VARCHAR(5)),4) QUANO   
				,U.EMP GAMMAN        
				,M.PRICE GAMGA, B.SUSU FEE, B.SUSU SUSU    
				,CASE WHEN ISNULL(CUSTCHARGE,'') = '' THEN CLIENT ELSE CUSTCHARGE END CLIENT, CAST(ISNULL(CUSTPHONE,'') AS VARCHAR(20)) AS CUSTPHONE     
				
				,MAX(CASE WHEN GUBUN_CODE = 'SBC' THEN 34 
				 WHEN T.COMMONCODE LIKE '6%' THEN 35 
				 WHEN GUBUN_CODE IN ('LAN','TEM') THEN 5
				 WHEN C.CODE IS NOT NULL THEN C.CODE 
				 WHEN CUST.CODE IS NOT NULL THEN CUST.CODE  
				 --WHEN  IWCUST.CUSTNAME IS NOT NULL THEN IWCUST.CODE 
				 WHEN CUSTNAME LIKE '%농협은행%' THEN 39 
				  WHEN CUSTNAME LIKE '%충청남도금산교육지원청교육장%' THEN 4 
				-- WHEN CUSTNAME LIKE '%수협은행%' THEN 46 
				
				-- WHEN CUSTNAME LIKE '%하나은행%' THEN 42 
				-- WHEN CUSTNAME LIKE '%우리은행%' THEN 37 
				-- WHEN CUSTNAME LIKE '%신한은행%' THEN 40 
				 WHEN CUSTNAME LIKE '%중진공%' OR CUSTNAME LIKE '%중소기업진흥%' THEN 34   
				 WHEN CUSTNAME LIKE '%농협%' And CUSTNAME Not Like '%농협은행%' THEN 55
				 WHEN CUSTNAME LIKE '%수협%' And CUSTNAME Not Like '%수협은행%' THEN 72
				 WHEN CUSTNAME LIKE '(주)%' OR CUSTNAME LIKE '%주식회사%' THEN 57 
				 WHEN DATALENGTH(CUSTNAME) = 6 THEN 58 ELSE NULL  END) [CUSTCODE]  
				  
				,REPLACE(SUBSTRING(MAX(CASE WHEN SubString(Z.REG, 1, 5) <> '' THEN Z.REG ELSE I.REG END),1,5),' ','') [REG]      
				,REPLACE(SUBSTRING(MAX(CASE WHEN SubString(Z.REG, 6, 5) <> '' THEN Z.REG ELSE I.REG END),6,5),' ','') [EUB]    
				,REPLACE(SUBSTRING(MAX(CASE WHEN SubString(Z.REG, 11, 1) <> '' THEN Z.REG ELSE I.REG END),11,1),' ','') [SAN]    
				,REPLACE(SUBSTRING(MAX(CASE WHEN SubString(Z.REG, 12, 4) <> '' THEN Z.REG ELSE I.REG END),12,4),' ','') [BUN1]    
				,REPLACE(SUBSTRING(MAX(CASE WHEN SubString(Z.REG, 16, 4) <> '' THEN Z.REG ELSE I.REG END),16,4),' ','') [BUN2]           
				,MAX(CASE Z.CODE WHEN 1 THEN Z.CODE ELSE NULL END) [CATEGORY1]
				,SUM(CASE Z.CODE WHEN 1 THEN AMT ELSE NULL END) [PRICE1]  
				,SUM(CASE Z.CODE WHEN 1 THEN CNT ELSE NULL END) [CNT1]  
				,MAX(CASE Z.CODE WHEN 2 THEN Z.CODE ELSE NULL END) [CATEGORY2] 
				,SUM(CASE Z.CODE WHEN 2 THEN AMT ELSE NULL END) [PRICE2]  
				,SUM(CASE Z.CODE WHEN 2 THEN CNT ELSE NULL END) [CNT2]  
				,MAX(CASE Z.CODE WHEN 3 THEN Z.CODE ELSE NULL END) [CATEGORY3] 
				,SUM(CASE Z.CODE WHEN 3 THEN AMT ELSE NULL END) [PRICE3]  
				,SUM(CASE Z.CODE WHEN 3 THEN CNT ELSE NULL END) [CNT3]  
				,MAX(CASE Z.CODE WHEN 4 THEN Z.CODE ELSE NULL END) [CATEGORY4] 
				,SUM(CASE Z.CODE WHEN 4 THEN AMT ELSE NULL END) [PRICE4]  
				,SUM(CASE Z.CODE WHEN 4 THEN CNT ELSE NULL END) [CNT4]  
				,MAX(CASE Z.CODE WHEN 7 THEN Z.CODE ELSE NULL END) [CATEGORY5] 
				,SUM(CASE Z.CODE WHEN 7 THEN AMT ELSE NULL END) [PRICE5]  
				,SUM(CASE Z.CODE WHEN 7 THEN CNT ELSE NULL END) [CNT5]  
				,MAX(CASE Z.CODE WHEN 12 THEN Z.CODE ELSE NULL END) [CATEGORY6]
				,SUM(CASE Z.CODE WHEN 12 THEN AMT ELSE NULL END) [PRICE6]  
				,SUM(CASE Z.CODE WHEN 12 THEN CNT ELSE NULL END) [CNT6]  
				,MAX(CASE Z.CODE WHEN 16 THEN Z.CODE ELSE NULL END) [CATEGORY7]
				,SUM(CASE Z.CODE WHEN 16 THEN AMT ELSE NULL END) [PRICE7]  
				,SUM(CASE Z.CODE WHEN 16 THEN CNT ELSE NULL END) [CNT7]  
				,MAX(CASE Z.CODE WHEN 18 THEN Z.CODE ELSE NULL END) [CATEGORY8]
				,SUM(CASE Z.CODE WHEN 18 THEN AMT ELSE NULL END) [PRICE8]  
				,SUM(CASE Z.CODE WHEN 18 THEN CNT ELSE NULL END) [CNT8]  
				,MAX(CASE Z.CODE WHEN 19 THEN Z.CODE ELSE NULL END) [CATEGORY9]
				,SUM(CASE Z.CODE WHEN 19 THEN AMT ELSE NULL END) [PRICE9]  
				,SUM(CASE Z.CODE WHEN 19 THEN CNT ELSE NULL END) [CNT9]  
				,M.GUBUN_CODE, M.BUB_CD, M.SA_NO, M.ORD_HOI  
	INTO #TEMP  
	FROM APW_MASTER M    
		JOIN #SEL A ON M.MASTERID = A.ID  
		LEFT JOIN APW_REPAPP_CUST CUST ON --M.CUSTNAME LIKE '%'+CUST.NAME+'%'  
															(M.CUSTNAME = '경기도지방토지수용위원회위원장' And Cust.NAME like '%지방토지수용위원회%')
															Or (M.CUSTNAME <> '경기도지방토지수용위원회위원장' And M.CUSTNAME like '%'+CUST.NAME+'%' ) -- 2020.12.29 YJI 변경
		--LEFT JOIN APW_IW_REPP_CUSTNAME IWCUST ON M.CUSTNAME LIKE '%'+IWCUST.CUSTNAME+'%'  
		LEFT JOIN APW_BILL B ON M.MASTERID = B.MASTERID    
		LEFT JOIN APW_DOCUMENT D ON M.MASTERID = D.MASTERID  
		LEFT JOIN APW_PURPOSE T ON M.PURPOSE = T.CODE   
		LEFT JOIN DBO.TMWCMN_USR_BAC_INFO U ON M.SIGNER = U.USR_SEQ   
		LEFT JOIN #I AS I ON M.MASTERID = I.MASTERID    
		LEFT JOIN APW_REPAPP_CUST C ON A.LINKNAME LIKE C.NAME+'%'  
		--일우 추가 2020.04.13  건명 전례에서 가져오기
		LEFT JOIN JUN_MASTER J ON M.DocID = J.ID_NUM
		LEFT JOIN (  
		--물건상세별로 건수와 평가액을 산출... (물건상세는 SELECT * FROM APW_REPAPP_CATEGORY 코드 참조)  
		--괄호감정표 내용을 RDB로 가지고 있다면 그곳에서 산출하는등 각 법인에 맞게 수정할것  
		SELECT A.APPCODE, A.ID_NUM
					,CASE ETYPE_CD WHEN '10' THEN 4 --자동차   
												 WHEN '20' THEN 3 --건설기계   
												 WHEN '30' THEN 7 --7 상선(화물선/여객선) 8 특수작업선(드릴쉽/쇄빙선 등) 9 함정 10 보트/요트   
												 WHEN '40' THEN 12 -- 11 헬리콥터 12 비행기  
												 WHEN '50' THEN 18 -- 광업권   
												 WHEN '60' THEN 19 -- 어업권  
												 ELSE 16 END [CODE] -- 기타기계  
					,NULL [REG], COUNT(*) [CNT], SUM(EKUM) [AMT]  
		FROM JUN_ETC A  
			JOIN #SEL B ON B.BUNGI = '{BUNGI}' AND B.MON = {MON} AND A.APPCODE = B.APPCODE AND A.ID_NUM = B.ID_NUM  
		WHERE EKUM > 0  
		GROUP BY A.APPCODE, A.ID_NUM, CASE ETYPE_CD WHEN '10' THEN 4 WHEN '20' THEN 3 WHEN '30' THEN 7 WHEN '40' THEN 12 WHEN '50' THEN 18 WHEN '60' THEN 19 ELSE 16 END   
		UNION ALL  
		SELECT A.APPCODE, A.ID_NUM, 1 CODE, MAX(A.SREG+A.SEUB+A.SSAN+A.SBUN1+A.SBUN2) REG, COUNT(*) CNT, SUM(TKUM) AMT  
		FROM [JUN_LAND] A   
			JOIN #SEL B ON B.BUNGI = '{BUNGI}' AND B.MON = {MON} AND A.APPCODE = B.APPCODE AND A.ID_NUM = B.ID_NUM   
		GROUP BY A.APPCODE, A.ID_NUM  
		UNION ALL  
		SELECT A.APPCODE, A.ID_NUM, 1, MAX(A.SREG+A.SEUB+A.SSAN+A.SBUN1+A.SBUN2) , COUNT(*) CNT, SUM(TKUM)   
		FROM [JUN_BLAND] A   
		  JOIN #SEL B ON B.BUNGI = '{BUNGI}' AND B.MON = {MON} AND A.APPCODE = B.APPCODE AND A.ID_NUM = B.ID_NUM  
		GROUP BY A.APPCODE, A.ID_NUM  
		UNION ALL  
		SELECT A.APPCODE, A.ID_NUM, 2, MAX(A.SREG+A.SEUB+A.SSAN+A.SBUN1+A.SBUN2)  REG, COUNT(*) CNT, SUM(GKUM) AMT  
		FROM [JUN_BUILD] A   
			JOIN #SEL B ON B.BUNGI = '{BUNGI}' AND B.MON = {MON} AND A.APPCODE = B.APPCODE AND A.ID_NUM = B.ID_NUM  
		GROUP BY A.APPCODE, A.ID_NUM  
		UNION ALL  
		SELECT A.APPCODE, A.ID_NUM, 2, MAX(A.SREG+A.SEUB+A.SSAN+A.SBUN1+A.SBUN2)  REG, COUNT(*) CNT, SUM(GKUM) AMT  
		FROM [JUN_BBUILD] A   
		  JOIN #SEL B ON B.BUNGI = '{BUNGI}' AND B.MON = {MON} AND A.APPCODE = B.APPCODE AND A.ID_NUM = B.ID_NUM  
		GROUP BY A.APPCODE, A.ID_NUM  
		UNION ALL  
		SELECT A.APPCODE, A.ID_NUM, 2, MAX(A.SREG+A.SEUB+A.SSAN+A.SBUN1+A.SBUN2)  REG, COUNT(*) CNT, SUM(AKUM) AMT  
		FROM [JUN_APT] A   
			JOIN #SEL B ON B.BUNGI = '{BUNGI}' AND B.MON = {MON} AND A.APPCODE = B.APPCODE AND A.ID_NUM = B.ID_NUM  
		GROUP BY A.APPCODE, A.ID_NUM      
		) Z ON A.APPCODE = Z.APPCODE AND A.ID_NUM = Z.ID_NUM   
	WHERE A.FUSE = 'Y' AND A.BUNGI = '{BUNGI}' AND A.MON = {MON} AND A.APPCODE = '{APPCODE}'  
	  
	GROUP BY A.ID_NUM, T.COMMONCODE, CASE M.GUBUN_CODE WHEN 'CTS' THEN '60' WHEN 'LAN' THEN '50' WHEN 'TKP' THEN '70' ELSE T.YCODE END  
	, CAST(M.TITLE AS VARCHAR(120))   --일우 주석 2020.04.13
	, CAST(J.GNAME AS VARCHAR(120))  
	, CAST(M.CUSTNAME AS VARCHAR(60))  
	, M.RECEIPTDATE, M.SENDDATE, D.PRICEPOINTDATE  
	, RIGHT('00'+CAST(CAST(U.QUA_NO AS INT) AS VARCHAR(5)),4)  
	, U.EMP, M.PRICE, B.SUSU, CASE WHEN ISNULL(CUSTCHARGE,'') = '' THEN CLIENT ELSE CUSTCHARGE END, CAST(ISNULL(CUSTPHONE,'') AS VARCHAR(20))  
	, M.GUBUN_CODE, M.BUB_CD, M.SA_NO, M.ORD_HOI  

	SELECT BUNGI, APPCODE, ID_NUM, PCODE, YCODE, GNAME, CUST, IN_DATE, OUTDATE, CONSULTDATE,  
	 QUANO, GAMMAN, GAMGA, SUSU, FEE, CLIENT, CUSTPHONE, CUSTCODE,   
	 CASE WHEN DATALENGTH(REG) = 5 THEN REG ELSE '' END,   
	 CASE WHEN DATALENGTH(EUB) = 5 THEN EUB ELSE '' END,   
	 CASE WHEN DATALENGTH(SAN) = 1 THEN SAN ELSE '' END,   
	 CASE WHEN DATALENGTH(BUN1) = 4 THEN BUN1 ELSE '0000' END,   
	 CASE WHEN DATALENGTH(BUN2) = 4 THEN BUN2 ELSE '0000' END,      
	 CATEGORY1, PRICE1, CNT1, CATEGORY2, PRICE2, CNT2, CATEGORY3, PRICE3, CNT3, CATEGORY4, PRICE4, CNT4, CATEGORY5, PRICE5, CNT5,   
	 CATEGORY6, PRICE6, CNT6, CATEGORY7, PRICE7, CNT7, CATEGORY8, PRICE8, CNT8, CATEGORY9, PRICE9, CNT9,   
	 GUBUN_CODE, BUB_CD, SA_NO, ORD_HOI, {MON}
	FROM #TEMP
